name: Deploy to GKE

on:
  push:
    branches:
      - main  # main ブランチに push されたときに実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t rick0036/fastapi-gke:latest .

      - name: Push Docker image
        run: |
          docker push rick0036/fastapi-gke:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials gke-demo-cluster --region=us-central1

      - name: Deploy to GKE
        run: |
          kubectl apply -f fastapi-deployment.yaml
          kubectl apply -f fastapi-ingress.yaml
